### ISSUE TITLE
How to put it in Docker Desktop?

### ISSUE THREAD

**Issue by lp85d** [nunocoracao/welcome-to-volumes#31]
Microsoft Windows [Version 10.0.22621.2428]
(c) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

C:\Windows\System32>git clone https://github.com/docker/multi-container-app
`Cloning into 'multi-container-app'...
remote: Enumerating objects: 2307, done.
remote: Counting objects: 100% (39/39), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 2307 (delta 11), reused 26 (delta 11), pack-reused 2268
Receiving objects: 100% (2307/2307), 3.83 MiB | 2.79 MiB/s, done.
Resolving deltas: 100% (366/366), done.`

C:\Windows\System32>cd multi-container-app

C:\Windows\System32\multi-container-app>docker build -t multi-container-app .

`[+] Building 0.0s (0/0)  docker:default
2024/06/05 23:06:00 http2: server: error reading preface from client //./pipe/docker_engine: file has already been close[+] Building 0.1s (1/1) FINISHED                                                                         docker:default
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 2B                                                                                 0.0s
ERROR: failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory`
`View build details: docker-desktop://dashboard/build/default/default/uxwi1u2piw4n36pfdbwax30l9`

**Comment by lp85d** [comment]
А понял!
Сам проект имеет такую структуру
C:\Windows\System32>tree C:\Windows\System32\multi-container-app /f
Структура папок тома Windows 11
Серийный номер тома: 3054-345D
C:\WINDOWS\SYSTEM32\MULTI-CONTAINER-APP
│   .DS_Store
│   .gitignore
│   compose.yaml
│   README.md
│
└───app
    │   .dockerignore
    │   .DS_Store
    │   Dockerfile
    │   package-lock.json
    │   package.json
    │   server.js
    │
    ├───config
    │       keys.js
    │
    ├───models
    │       Todo.js
    │
    ├───routes
    │       front.js
    │
    └───views
            todos.ejs

**Comment by lp85d** [comment]
Получилось!
C:\Windows\System32\multi-container-app>cd app
C:\Windows\System32\multi-container-app\app>docker build -t multi-container-app .
2024-06-05 23:40:21 
2024-06-05 23:40:21 > multi-container-apps@1.0.0 dev
2024-06-05 23:40:21 > nodemon -e js,ejs server.js
2024-06-05 23:40:21 
2024-06-05 23:40:21 [nodemon] 3.0.1
2024-06-05 23:40:21 [nodemon] to restart at any time, enter `rs`
2024-06-05 23:40:21 [nodemon] watching path(s): *.*
2024-06-05 23:40:21 [nodemon] watching extensions: js,ejs
2024-06-05 23:40:21 [nodemon] starting `node server.js`
2024-06-05 23:40:22 Server listening on port 3000
2024-06-05 23:40:52 MongooseServerSelectionError: getaddrinfo ENOTFOUND todo-database
2024-06-05 23:40:52     at _handleConnectionErrors (/usr/src/app/node_modules/mongoose/lib/connection.js:809:11)
2024-06-05 23:40:52     at NativeConnection.openUri (/usr/src/app/node_modules/mongoose/lib/connection.js:784:11)
2024-06-05 23:40:52     at processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-06-05 23:40:52     at runNextTicks (node:internal/process/task_queues:64:3)
2024-06-05 23:40:52     at listOnTimeout (node:internal/timers:537:9)
2024-06-05 23:40:52     at process.processTimers (node:internal/timers:511:7) {
2024-06-05 23:40:52   reason: TopologyDescription {
2024-06-05 23:40:52     type: 'Unknown',
2024-06-05 23:40:52     servers: Map(1) { 'todo-database:27017' => [ServerDescription] },
2024-06-05 23:40:52     stale: false,
2024-06-05 23:40:52     compatible: true,
2024-06-05 23:40:52     heartbeatFrequencyMS: 10000,
2024-06-05 23:40:52     localThresholdMS: 15,
2024-06-05 23:40:52     setName: null,
2024-06-05 23:40:52     maxElectionId: null,
2024-06-05 23:40:52     maxSetVersion: null,
2024-06-05 23:40:52     commonWireVersion: 0,
2024-06-05 23:40:52     logicalSessionTimeoutMinutes: null
2024-06-05 23:40:52   },
2024-06-05 23:40:52   code: undefined
2024-06-05 23:40:52 }

**Comment by lp85d** [comment]
Получается таким образом я добавляю C:\Windows\System32\multi-container-app\compose.yaml в Docker Desktop
После чего устанавливаю все добавленные композеры
C:\Windows\System32\multi-container-app>docker compose up -d
[+] Running 9/9
 ✔ todo-database Pulled                                                                                           54.8s
   ✔ 7646c8da3324 Pull complete                                                                                    7.9s
   ✔ ed43470d3455 Pull complete                                                                                    7.9s
   ✔ d06bb5e0759e Pull complete                                                                                    8.2s
   ✔ 1744a61682a8 Pull complete                                                                                    8.2s
   ✔ bf90a833dd2f Pull complete                                                                                    8.3s
   ✔ b87df9d85182 Pull complete                                                                                    8.3s
   ✔ 11f578d2a329 Pull complete                                                                                   49.2s
   ✔ 555a62b8f2fd Pull complete                                                                                   50.7s
2024/06/05 23:47:23 http2: server: error reading preface from client //./pipe/docker_engine: file has already been closed
[+] Building 16.5s (15/15) FINISHED                                                                      docker:default
 => [todo-app internal] load build definition from Dockerfile                                                      0.5s
 => => transferring dockerfile: 1.29kB                                                                             0.0s
 => [todo-app] resolve image config for docker-image://docker.io/docker/dockerfile:1                              11.3s
 => [todo-app auth] docker/dockerfile:pull token for registry-1.docker.io                                          0.0s
 => CACHED [todo-app] docker-image://docker.io/docker/dockerfile:1@sha256:a57df69d0ea827fb7266491f2813635de6f1726  0.0s
 => [todo-app internal] load metadata for docker.io/library/node:19.5.0-alpine                                     1.6s
 => [todo-app auth] library/node:pull token for registry-1.docker.io                                               0.0s
 => [todo-app internal] load .dockerignore                                                                         0.2s
 => => transferring context: 706B                                                                                  0.0s
 => [todo-app stage-0 1/6] FROM docker.io/library/node:19.5.0-alpine@sha256:4619ec6c9a43ab4edfa12cf96745319c3ca43  0.0s
 => [todo-app internal] load build context                                                                         0.3s
 => => transferring context: 370B                                                                                  0.0s
 => CACHED [todo-app stage-0 2/6] WORKDIR /usr/src/app                                                             0.0s
 => CACHED [todo-app stage-0 3/6] RUN --mount=type=bind,source=package.json,target=package.json     --mount=type=  0.0s
 => CACHED [todo-app stage-0 4/6] RUN npm install -g nodemon                                                       0.0s
 => CACHED [todo-app stage-0 5/6] COPY . .                                                                         0.0s
 => CACHED [todo-app stage-0 6/6] RUN  chown -R node /usr/src/app                                                  0.0s
 => [todo-app] exporting to image                                                                                  0.4s
 => => exporting layers                                                                                            0.0s
 => => writing image sha256:bce4ca6530d9d3a4111688f7703564def72542bb8bc10b238df5d6c9f2f448dd                       0.0s
 => => naming to docker.io/library/multi-container-app-todo-app                                                    0.1s
[+] Running 3/3
 ✔ Network multi-container-app_default            Created                                                          0.3s
 ✔ Container multi-container-app-todo-database-1  Started                                                          2.4s
 ✔ Container multi-container-app-todo-app-1       Started                                                          2.9s

**Comment by lp85d** [comment]
![image](https://github.com/docker/multi-container-app/assets/3320759/6442e596-4195-40f2-b2db-49a36ec4696c)
![image](https://github.com/docker/multi-container-app/assets/3320759/05eee168-626d-4547-af6e-88aef96493f2)

**Comment by lp85d** [comment]
![image](https://github.com/docker/multi-container-app/assets/3320759/043546dc-2c4a-4137-adff-4db64ff9aad6)

**Comment by lp85d** [comment]
![image](https://github.com/docker/multi-container-app/assets/3320759/0a84aea9-678e-4329-9b5b-630611d4b73d)
